Issue-9: Add initial support for Validation
jlmorgan/node-functional-extras pull request #14
Opened 2019-08-17 21:11 UTC by jlmorgan

- [ ] Squash commits before merging.

closes #9
SemVer:Minor
enhancement

2019-08-27 18:20 UTC, doomchild requested changes
Minor documentation formatting stuff is needed.

2019-08-27 18:20 UTC, doomchild commented on src/data/Functions/requireFunction.js
> + * Throws an {@link TypeError} if the {@code value} provided is not an {@link Function}.
`an` -> `a`

2019-08-27 18:20 UTC, doomchild commented on src/data/Validation/Validation.js
> +   * Determine whether or not the {@code other} has the same value as the current {@code instance}.
You have "Determine" here, but "Determines" on other predicates.

2019-08-27 18:20 UTC, doomchild commented on src/data/Validation/requireValidation.js
> + * Throws an {@link TypeError} if the {@code value} provided is not a {@code Validation}.
`an` -> `a`

2019-08-27 18:20 UTC, doomchild commented on src/requireType.js
> + * Throws an {@link TypeError} if the {@code value} provided fails the {@code predicate}.
`an` -> `a`

2019-08-30 02:52 UTC, jlmorgan commented on src/data/Functions/requireFunction.js
> + * Throws an {@link TypeError} if the {@code value} provided is not an {@link Function}.
Fixed.

2019-08-30 02:52 UTC, jlmorgan commented on src/data/Validation/requireValidation.js
> + * Throws an {@link TypeError} if the {@code value} provided is not a {@code Validation}.
Fixed.

2019-08-30 02:52 UTC, jlmorgan commented on src/requireType.js
> + * Throws an {@link TypeError} if the {@code value} provided fails the {@code predicate}.
Fixed.

2019-08-30 02:52 UTC, jlmorgan commented on src/data/Validation/Validation.js
> +   * Determine whether or not the {@code other} has the same value as the current {@code instance}.
Fixed.

2019-08-30 15:47 UTC, doomchild commented on src/data/Functions/requireFunction.js
> + * Throws an {@link TypeError} if the {@code value} provided is not an {@link Function}.
Wait, I'm dumb.  This _should_ be `a`.  Sorry.

2019-08-30 15:48 UTC, doomchild commented on src/data/Validation/requireValidation.js
> + * Throws an {@link TypeError} if the {@code value} provided is not a {@code Validation}.
My grammar brain must have been doing something else.  It was correct originally.

2019-08-30 15:48 UTC, doomchild commented on src/requireType.js
> + * Throws an {@link TypeError} if the {@code value} provided fails the {@code predicate}.
My grammar brain must have been doing something else. It was correct originally.

2019-08-31 01:57 UTC, jlmorgan commented on src/data/Functions/requireFunction.js
> + * Throws an {@link TypeError} if the {@code value} provided is not an {@link Function}.
I knew what you meant. = )

2019-09-01 17:43 UTC, doomchild approved these changes
Seems legit.

2019-09-01 19:06 UTC, merged